apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bgvt3ci6v-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bgvt3ci6v-java-quarkus-gitops